# calculate_distance function rewrite
We will be rewriting the calculate_distance function to use properties of NumPy arrays

In [22]:
import math
import numpy as np

def calculate_distance(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    Parameters
    ----------
    coord1, coord2: list
        The atomic coordinates
    box_length : float
        The box length. If given, the minimum image convention will be used to calculate the distance.

    Returns
    -------
    distance: float
        The distance between the two points.
    """
    distance = 0
    for i in range(3):
        dim_dist = (coord1[i] - coord2[i])
        if box_length:
            dim_dist = dim_dist - box_length * round(dim_dist / box_length)
        dim_dist = dim_dist**2
        distance += dim_dist
    distance = math.sqrt(distance)
    return distance

def calculate_distance_np(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    Parameters
    ----------
    coord1, coord2: np.ndarray
        The atomic coordinates
    box_length : float
        The box length. If given, the minimum image convention will be used to calculate the distance.

    Returns
    -------
    distance: float
        The distance between the two points.
    """
    
    coord_dist = coord1 - coord2
    if box_length:
        coord_dist = coord_dist - box_length * np.round(coord_dist / box_length)
    if coord_dist.ndim < 2:
        coord_dist = coord_dist.reshape(1, -1)
    coord_dist = coord_dist ** 2
    coord_dist_sum = coord_dist.sum(axis=1)
    distance = np.sqrt(coord_dist_sum)
    return distance

In [23]:
point1 = np.array([0,0,0])
point2 = np.array([0,0,8])

calculate_distance_np(point1, point2, 10)

array([2.])

In [3]:
dimensional_distance = point1 - point2
print(dimensional_distance)

[ 0  0 -8]


In [4]:
dd2 = dimensional_distance ** 2

In [5]:
dd2_sum = dd2.sum()
dd2_sum

64

In [6]:
distance = math.sqrt(dd2_sum)

In [14]:
coord_set1 = np.array([[0, 0, 0], [0,1,0]])
coord_set2 = np.array([[0,8,0], [0, 1.5, 0]])

In [20]:
calculate_distance_np(coord_set1, coord_set2, 10)

array([2. , 0.5])

In [21]:
point1.ndim

1